# Generated by Django 4.2 on 2023-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="community_partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="job_opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, null=True)),
                ("keywords", models.CharField(max_length=200, null=True)),
                ("community_partner_id", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="opportunity_to_student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opportunity_id", models.IntegerField(default=0, null=True)),
                ("student_id", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_email", models.EmailField(max_length=254)),
                ("student_id", models.IntegerField(default=0, null=True)),
                ("password", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
